//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from F:/Requisites/University/Compiler/Project/Phase 1/COOL_Parser\COOL.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ANTLR_COOL_Program {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICOOLListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class COOLBaseListener : ICOOLListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="COOLParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] COOLParser.ProgramContext context) { System.Console.WriteLine("enter program"); }
	/// <summary>
	/// Exit a parse tree produced by <see cref="COOLParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] COOLParser.ProgramContext context) { System.Console.WriteLine("exit program"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>classes</c>
	/// labeled alternative in <see cref="COOLParser.programBlocks"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClasses([NotNull] COOLParser.ClassesContext context) { System.Console.WriteLine("enter classes"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>classes</c>
	/// labeled alternative in <see cref="COOLParser.programBlocks"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClasses([NotNull] COOLParser.ClassesContext context) { System.Console.WriteLine("exit classes"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>eof</c>
	/// labeled alternative in <see cref="COOLParser.programBlocks"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEof([NotNull] COOLParser.EofContext context) { System.Console.WriteLine("enter end of file"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>eof</c>
	/// labeled alternative in <see cref="COOLParser.programBlocks"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEof([NotNull] COOLParser.EofContext context) { System.Console.WriteLine("exit end of ifle"); }
	/// <summary>
	/// Enter a parse tree produced by <see cref="COOLParser.classDefine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDefine([NotNull] COOLParser.ClassDefineContext context) { System.Console.WriteLine("enter class define"); }
	/// <summary>
	/// Exit a parse tree produced by <see cref="COOLParser.classDefine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDefine([NotNull] COOLParser.ClassDefineContext context) { System.Console.WriteLine("exit class define"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>method</c>
	/// labeled alternative in <see cref="COOLParser.feature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod([NotNull] COOLParser.MethodContext context) { System.Console.WriteLine("enter method"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>method</c>
	/// labeled alternative in <see cref="COOLParser.feature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod([NotNull] COOLParser.MethodContext context) { System.Console.WriteLine("exit method"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>property</c>
	/// labeled alternative in <see cref="COOLParser.feature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty([NotNull] COOLParser.PropertyContext context) { System.Console.WriteLine("enter property"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>property</c>
	/// labeled alternative in <see cref="COOLParser.feature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty([NotNull] COOLParser.PropertyContext context) { System.Console.WriteLine("exit property"); }
	/// <summary>
	/// Enter a parse tree produced by <see cref="COOLParser.formal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormal([NotNull] COOLParser.FormalContext context) { System.Console.WriteLine("enter formal"); }
	/// <summary>
	/// Exit a parse tree produced by <see cref="COOLParser.formal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormal([NotNull] COOLParser.FormalContext context) { System.Console.WriteLine("exit formal"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>letIn</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLetIn([NotNull] COOLParser.LetInContext context) { System.Console.WriteLine("enter letIn"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>letIn</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLetIn([NotNull] COOLParser.LetInContext context) { System.Console.WriteLine("exit letIn"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>minus</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMinus([NotNull] COOLParser.MinusContext context) { System.Console.WriteLine("enter minus"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>minus</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMinus([NotNull] COOLParser.MinusContext context) { System.Console.WriteLine("exit minus"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>string</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] COOLParser.StringContext context) { System.Console.WriteLine("enter string"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>string</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] COOLParser.StringContext context) { System.Console.WriteLine("exit string"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>isvoid</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIsvoid([NotNull] COOLParser.IsvoidContext context) { System.Console.WriteLine("enter IsVoid"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>isvoid</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIsvoid([NotNull] COOLParser.IsvoidContext context) { System.Console.WriteLine("exit IsVoid"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>while</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhile([NotNull] COOLParser.WhileContext context) { System.Console.WriteLine("enter while"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>while</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhile([NotNull] COOLParser.WhileContext context) { System.Console.WriteLine("exit while"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>division</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDivision([NotNull] COOLParser.DivisionContext context) { System.Console.WriteLine("enter Division"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>division</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDivision([NotNull] COOLParser.DivisionContext context) { System.Console.WriteLine("exit Division"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>negative</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNegative([NotNull] COOLParser.NegativeContext context) { System.Console.WriteLine("enter Negative"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>negative</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNegative([NotNull] COOLParser.NegativeContext context) { System.Console.WriteLine("exit Negative"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>boolNot</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolNot([NotNull] COOLParser.BoolNotContext context) { System.Console.WriteLine("enter BoolNot"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>boolNot</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolNot([NotNull] COOLParser.BoolNotContext context) { System.Console.WriteLine("exit BoolNot"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>lessThan</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLessThan([NotNull] COOLParser.LessThanContext context) { System.Console.WriteLine("enter LessThan"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>lessThan</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLessThan([NotNull] COOLParser.LessThanContext context) { System.Console.WriteLine("exit LessThan"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>block</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] COOLParser.BlockContext context) { System.Console.WriteLine("enter Block"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>block</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] COOLParser.BlockContext context) { System.Console.WriteLine("exit Block"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>id</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterId([NotNull] COOLParser.IdContext context) { System.Console.WriteLine("enter Id"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>id</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitId([NotNull] COOLParser.IdContext context) { System.Console.WriteLine("exit Id"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>multiply</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiply([NotNull] COOLParser.MultiplyContext context) { System.Console.WriteLine("enter Multiply"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>multiply</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiply([NotNull] COOLParser.MultiplyContext context) { System.Console.WriteLine("exit Multiply"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>if</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf([NotNull] COOLParser.IfContext context) { System.Console.WriteLine("enter If"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>if</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf([NotNull] COOLParser.IfContext context) { System.Console.WriteLine("exit If"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>case</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCase([NotNull] COOLParser.CaseContext context) { System.Console.WriteLine("enter Case"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>case</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCase([NotNull] COOLParser.CaseContext context) { System.Console.WriteLine("exit Case"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>ownMethodCall</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOwnMethodCall([NotNull] COOLParser.OwnMethodCallContext context) { System.Console.WriteLine("enter OwnMethodCall"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>ownMethodCall</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOwnMethodCall([NotNull] COOLParser.OwnMethodCallContext context) { System.Console.WriteLine("exit OwnMethodCall"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>add</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdd([NotNull] COOLParser.AddContext context) { System.Console.WriteLine("enter Add"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>add</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdd([NotNull] COOLParser.AddContext context) { System.Console.WriteLine("exit Add"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>new</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNew([NotNull] COOLParser.NewContext context) { System.Console.WriteLine("enter New"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>new</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNew([NotNull] COOLParser.NewContext context) { System.Console.WriteLine("exit New"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>parentheses</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParentheses([NotNull] COOLParser.ParenthesesContext context) { System.Console.WriteLine("enter Parantheses"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>parentheses</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParentheses([NotNull] COOLParser.ParenthesesContext context) { System.Console.WriteLine("exit Parantheses"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>assignment</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] COOLParser.AssignmentContext context) { System.Console.WriteLine("enter Assignment"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>assignment</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] COOLParser.AssignmentContext context) { System.Console.WriteLine("exit Assignment"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>false</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFalse([NotNull] COOLParser.FalseContext context) { System.Console.WriteLine("enter False"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>false</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFalse([NotNull] COOLParser.FalseContext context) { System.Console.WriteLine("exit False"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>int</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInt([NotNull] COOLParser.IntContext context) { System.Console.WriteLine("enter Int"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>int</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInt([NotNull] COOLParser.IntContext context) { System.Console.WriteLine("exit Int"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>equal</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqual([NotNull] COOLParser.EqualContext context) { System.Console.WriteLine("enter Equal"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>equal</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqual([NotNull] COOLParser.EqualContext context) { System.Console.WriteLine("exit Equal"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>true</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrue([NotNull] COOLParser.TrueContext context) { System.Console.WriteLine("enter True"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>true</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrue([NotNull] COOLParser.TrueContext context) { System.Console.WriteLine("exit True"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>lessEqual</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLessEqual([NotNull] COOLParser.LessEqualContext context) { System.Console.WriteLine("enter LessEqual"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>lessEqual</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLessEqual([NotNull] COOLParser.LessEqualContext context) { System.Console.WriteLine("exit LessEqual"); }
	/// <summary>
	/// Enter a parse tree produced by the <c>methodCall</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodCall([NotNull] COOLParser.MethodCallContext context) { System.Console.WriteLine("enter MethodCall"); }
	/// <summary>
	/// Exit a parse tree produced by the <c>methodCall</c>
	/// labeled alternative in <see cref="COOLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodCall([NotNull] COOLParser.MethodCallContext context) { System.Console.WriteLine("exit MethodCall"); }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { /*System.Console.WriteLine("enter EveryRule");*/ }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { /*System.Console.WriteLine("exit EveryRule"); */}
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { System.Console.WriteLine("visit Terminal"); }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { System.Console.WriteLine("visit Error Node"); }
}
} // namespace ANTLR_COOL_Program
